package coop.miriv.enology.identity.service;
import coop.miriv.enology.common.exception.ConflictException;
import coop.miriv.enology.common.exception.NotFoundException;
import coop.miriv.enology.identity.dto.CenterAdminRequest;
import coop.miriv.enology.identity.dto.CenterOption;
import java.util.List;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service public class CenterAdminService { private final JdbcTemplate jdbc; private final CurrentUserProvider currentUser; public CenterAdminService(JdbcTemplate jdbc, CurrentUserProvider currentUser){this.jdbc=jdbc;this.currentUser=currentUser;} private void admin(){Boolean ok=jdbc.queryForObject("select exists(select 1 from app_user_role ur join role r on r.id=ur.role_id where ur.user_id=? and r.code='ADMIN')",Boolean.class,currentUser.requireCurrentUserId());if(!Boolean.TRUE.equals(ok))throw new AccessDeniedException("Administrator role required.");} public List<CenterOption> list(){admin();return jdbc.query("select code,name from center order by name",(rs,n)->new CenterOption(rs.getString(1),rs.getString(2)));} @Transactional public CenterOption create(CenterAdminRequest r){admin();try{jdbc.update("insert into center(code,name) values(?,?)",r.code().trim().toUpperCase(),r.name().trim());}catch(org.springframework.dao.DataIntegrityViolationException e){throw new ConflictException("Center code already exists.");}return new CenterOption(r.code().trim().toUpperCase(),r.name().trim());} @Transactional public CenterOption update(String code,CenterAdminRequest r){admin();int n=jdbc.update("update center set code=?,name=? where code=?",r.code().trim().toUpperCase(),r.name().trim(),code);if(n==0)throw new NotFoundException("Center not found.");return new CenterOption(r.code().trim().toUpperCase(),r.name().trim());} @Transactional public void delete(String code){admin();UUID id=jdbc.query("select id from center where code=?",(rs,n)->rs.getObject(1,UUID.class),code).stream().findFirst().orElseThrow(()->new NotFoundException("Center not found."));Integer refs=jdbc.queryForObject("select (select count(*) from app_user where center_id=?) + (select count(*) from zone where center_id=?) + (select count(*) from deposit where center_id=?)",Integer.class,id,id,id);if(refs!=null&&refs>0)throw new ConflictException("The center is still referenced by users, zones or deposits.");jdbc.update("delete from center where id=?",id);}}
